name: Example-call-workflow-workflow-ref

on: workflow_dispatch

jobs:
  call-remote-flow:
    uses: roelofvsr-org/test-oidc-workflow-ref/.github/workflows/Azure-OIDC-reusable-Example-reusable.yml@main
    secrets: inherit

  echo-message:
    runs-on: ubuntu-latest
    needs: call-remote-flow # This ensures the echo runs after the call-read-secret job
    steps:
      - name: Echo a message2
        run: echo "The remote workflow has been called!"

      - name: test
        run: az account list
